#!/bin/bash
. prj-export-variables

if [ ! -d "$WORKING_DIR" ]; then
  echo "working directory not set"
  exit
fi

startScript="#!/bin/bash\n"

### Get Project Name
while [[ -z $NAME ]]; do
  printf "Enter project name: "
  read NAME
  # check if name exists
  if [ -d "$WORKING_DIR$NAME" ]; then
    NAME=""
    echo "Project name already exists, try again."
  fi
done

### Get Git Repos
GIT_REPOS=()
CONTINUE=true
while [[ $CONTINUE = true ]]; do
  printf "Enter git repos, empty to finish: "
  read GIT
  # check if name is valid
  if [[ "$GIT" != "" ]]; then
    GIT_REPOS+=("$GIT")
  else
    CONTINUE=false
  fi
done


### setup project
#make project folders
PROJECT_DIR="$WORKING_DIR$NAME"
PROJECT_CONFIG_DIR="$PROJECT_DIR"/.config/
PROJECT_NEW_TAB_COMMANDS="$PROJECT_CONFIG_DIR"/new-tab-commands
mkdir -p "$PROJECT_CONFIG_DIR"
touch "$PROJECT_NEW_TAB_COMMANDS"

#pull git repos
for git in "${GIT_REPOS[@]}"; do
  prj-git-add "$NAME" "$git"
done

#write start script
echo -e $startScript > "$PROJECT_CONFIG_DIR"/start.sh
sudo chmod 755 "$PROJECT_CONFIG_DIR"/start.sh

cd "$WORKING_DIR"
git add "$NAME"
git commit -m "adding $NAME"
