#!/bin/bash
. prj-export-variables

if [ ! -d "$WORKING_DIR" ]; then
  echo "working directory not set"
  exit
fi

if [ -d "$WORKING_DIR$1" ]; then
  cd "$WORKING_DIR"
  git rm "$1"
else
  echo "project doesn't exists"
fi
