#!/bin/bash
. prj-export-variables

while [[ $# > 1 ]]; do
  key="$1"
  case $key in
  -w|--working-dir)
    WORKING="$2"
    shift
    ;;
  -e|--editor)
    NEW_EDITOR="$2"
    shift
    ;;
  -g|--git-client)
    NEW_GIT_CLIENT="$2"
    shift
    ;;
  -y|--use-yarn)
    NEW_USE_YARN="$2"
    shift
    ;;
  *)
    ;;
  esac
  shift
done

# set working dir
if [[ "$WORKING" ]]; then
  [ "${WORKING/#\//}" != "$WORKING" ] || WORKING="$CALLING_DIR"/"$WORKING"
  WORKING="${WORKING%/}"/
  mkdir -p "$WORKING"
  if [ "$WORKING" != "$WORKING_DIR" ]; then
    cd "$WORKING_DIR"
    if [ ! -z $WORKING_DIR ]; then
      mv "$WORKING_DIR"/* "$WORKING"
      mv "$WORKING_DIR"/.* "$WORKING" 2> /dev/null
    else
      cd "$WORKING"
      git init
    fi
    echo "$WORKING" > "$WORKING_DIR_FILE"
  fi
fi

# set editor
if [[ "$NEW_EDITOR" ]]; then
  echo "$NEW_EDITOR" > "$EDITOR_FILE"
fi

# set git client
if [[ "$NEW_GIT_CLIENT" ]]; then
  echo "$NEW_GIT_CLIENT" > "$GIT_CLIENT_FILE"
fi

if [[ "$NEW_USE_YARN" ]]; then
  echo "$NEW_USE_YARN" > "$USE_YARN_FILE"
fi
