#!/bin/bash
. prj-export-variables

if [ ! -d "$WORKING_DIR" ]; then
  echo "working directory not set"
  exit
fi

if [ ! -d "$ARCHIVE_DIR" ]; then
  echo "archive directory not set"
  exit
fi

if [ -d "$WORKING_DIR$1" ]; then
  sudo rm -r "$WORKING_DIR$1"
  rm "$SUBLIME_DIR$1".sublime-project
  # remove atom project
elif [ -d "$ARCHIVE_DIR$1" ]; then
  sudo rm -r "$ARCHIVE_DIR$1"
  rm "$SUBLIME_DIR$1".sublime-project
  # remove atom project
else
  echo "project doesn't exists"
fi
